apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oc-client-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - __HOST__
      secretName: client-on-track-ch-tls
  rules:
    - host: __HOST__
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oc-client-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: oc-client-backend
                port:
                  number: 80
