apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oc-client-ingress
  namespace: oc-client
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: client.on-track.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oc-client-frontend
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: oc-client-backend
                port:
                  number: 80
