name: Frontend CI/CD

on:
  push:
    branches: ['main', 'dev']
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: julienreichel/oc-infra/.github/workflows/reusable-build.yml@main
    with:
      image_name: ghcr.io/julienreichel/oc-client-frontend
    secrets: inherit

  deploy-prod:
    if: github.ref_name == 'main'
    uses: julienreichel/oc-infra/.github/workflows/reusable-deploy.yml@main
    with:
      app_kind: frontend
      image_name: ghcr.io/julienreichel/oc-client-frontend
      namespace: oc-client
      host: client.on-track.ch
    secrets: inherit

  deploy-dev:
    if: github.ref_name == 'dev'
    uses: julienreichel/oc-infra/.github/workflows/reusable-deploy.yml@main
    with:
      app_kind: frontend
      image_name: ghcr.io/julienreichel/oc-client-frontend
      namespace: oc-dev-client
      host: dev.client.on-track.ch
    secrets: inherit
